services:
  nginx:
    image: nginx:latest
    container_name: guitar-trackr_front
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=guitar-trackr.danielarroyo.dev
      - LETSENCRYPT_HOST=guitar-trackr.danielarroyo.dev
      - LETSENCRYPT_EMAIL=darroyo083@gmail.com
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Solo si usas React Router
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy
    external: true